## internal function that match the arguments provided to the correct
## row number in the data frame representing the Open Tree Taxonomy
## for a series of matched names.
check_args_match_names <- function(response, row_number, taxon_name, ott_id) {
    orig_order <- attr(response, "original_order")
    if (is.null(orig_order)) {
        stop(sQuote(substitute(response)), " was not created using ",
             sQuote("tnrs_match_names"))
    }

    if (missing(row_number) && missing(taxon_name) && missing(ott_id)) {
        stop("You must specify one of \'row_number\', \'taxon_name\' or \'ott_id\'.")
    } else if (!missing(row_number) && missing(taxon_name) && missing(ott_id)) {
        if (!is.numeric(row_number)) stop("\'row_number\' must be a numeric.")
        if (!row_number %in% orig_order) {
            stop("\'row_number\' is not a valid row number.")
        }
        i <- orig_order[row_number]
    } else if (missing(row_number) && !missing(taxon_name) && missing(ott_id)) {
        if (!is.character(taxon_name)) stop("\'taxon_name\' must be a character.")
        i <- orig_order[match(tolower(taxon_name), response$search_string)]
        if (any(is.na(i))) stop("Can't find ", taxon_name)
    } else if (missing(row_number) && missing(taxon_name) && !missing(ott_id)) {
        if (!check_numeric(ott_id)) stop("\'ott_id\" must look like a number.")
        i <- orig_order[match(ott_id, response$ott_id)]
        if (any(is.na(i))) stop("Can't find ", ott_id)
    } else {
        stop("You must use only one of \'row_number\', \'taxon_name\' or \'ott_id\'.")
    }

    if (length(i) > 1) stop("You must supply a single element for each argument.")
    i
}

##' Taxonomic names may have different meanings in different taxonomic
##' contexts, as the same genus name can be applied to animals and
##' plants for instance. Additionally, the meaning of a taxonomic name
##' may have change throughout its history, and may have referred to a
##' different taxon in the past. In such cases, a given names might
##' have multiple matches in the Open Tree Taxonomy. These functions
##' allow users to inspect (and update) alternative meaning of a given
##' name and its current taxonomic status according to the Open Tree
##' Taxonomy.
##'
##' To inspect alternative taxonomic meanings of a given name, you
##' need to provide the object resulting from a call to the
##' tnrs_match_names function, as well as one of either the row number
##' corresponding to the name in this object, the name itself (as used
##' in the original query), or the ott_id listed for this name.
##'
##' To update one of the name, you also need to provide the row number
##' in which the name to be replaced appear or its ott id.
##'
##' @title Inspect and Update alternative matches for a name returned by
##'     tnrs_match_names
##' @param response a data frame generated by the tnrs_match_names
##'     function
##' @param row_number the row number corresponding to the name to
##'     inspect
##' @param taxon_name the taxon name corresponding to the name to inspect
##' @param ott_id the ott id corresponding to the name to inspect
##' @return a data frame
##' @seealso \code{\link{tnrs_match_names}}
##' @examples
##'   \dontrun{
##'    matched_names <- tnrs_match_names(c("holothuria", "diadema", "boletus"))
##'    inspect_match_names(matched_names, taxon_name="diadema")
##'    new_matched_names <- update_match_names(matched_names, taxon_name="diadema",
##'                                            new_ott_id = 631176)
##'    new_matched_names
##'    }
##' @export
inspect_match_names <- function(response, row_number, taxon_name, ott_id) {

    i <- check_args_match_names(response, row_number, taxon_name, ott_id)

    res <- attr(response, "original_response")
    summary_match <- do.call("rbind", lapply(res$results[[i]]$match, function(x) {
            searchStr <- x$search_string
            uniqNames <- x$unique_name
            approxMatch <- x$is_approximate_match
            ott_id <- x$'ot:ottId'
            isSynonym <- x$is_synonym
            isDeprecated <- x$is_deprecated
            c(searchStr, uniqNames, approxMatch, ott_id, isSynonym, isDeprecated)
        }))
    summary_match <- data.frame(summary_match, stringsAsFactors=FALSE)
    names(summary_match) <- c("search_string", "unique_name", "approximate_match",
                              "ott_id", "is_synonym", "is_deprecated")
    summary_match
}


##' @param new_row_number the row number in the output of
##'     inspect_match_names to replace the taxa specified by
##'     \code{row_number}, \code{taxon_name}, or \code{ott_id}.
##' @param new_ott_id the ott id of the taxon to replace the taxa
##'     specified by \code{row_number}, \code{taxon_name}, or
##'     \code{ott_id}.
##' @export
##' @rdname inspect_match_names
update_match_names <- function(response, row_number, taxon_name, ott_id,
                               new_row_number, new_ott_id) {

    i <- check_args_match_names(response, row_number, taxon_name, ott_id)
    res <- attr(response, "original_response")
    tmpRes <- res$results[[i]]

    if (missing(row_number)) {
        if (!missing(taxon_name)) {
            rnb <- match(tolower(taxon_name), response$search_string)
        } else if (!missing(ott_id)) {
            rnb <- match(ott_id, response$ott_id)
        }
    } else {
        rnb <- row_number
    }

    if (missing(new_row_number) && missing(new_ott_id)) {
        stop("You must specify either \'new_row_number\' or \'new_ott_id\'")
    } else if (!missing(new_row_number) && missing(new_ott_id)) {
        if (! new_row_number %in% seq_len(length(tmpRes$matches)))
            stop("\'new_row_number\' is not a valid row number.")
        j <- new_row_number
    } else if (missing(new_row_number) && !missing(new_ott_id)) {
        allOttId <- sapply(tmpRes$matches, function(x) x$'ot:ottId')
        j <- match(new_ott_id, allOttId)
        if (any(is.na(j))) stop("Can't find ", new_ott_id)
    } else {
        stop("You must use only one of \'new_row_number\' or \'new_ott_id\'")
    }
    if (length(j) > 1) stop("You must supply a single element for each argument.")

    searchStr <- tmpRes$matches[[j]]$search_string
    uniqNames <- tmpRes$matches[[j]]$unique_name
    approxMatch <- tmpRes$matches[[j]]$is_approximate_match
    ott_id <- tmpRes$matches[[j]]$'ot:ottId'
    isSynonym <- tmpRes$matches[[j]]$is_synonym
    isDeprecated <- tmpRes$matches[[j]]$is_deprecated
    nMatch <- length(tmpRes$match)
    response[rnb, ] <- c(searchStr, uniqNames, approxMatch, ott_id, nMatch, isSynonym, isDeprecated)
    response
}

##' When querying the Taxonomic Name Resolution Services for a
##' particular taxonomic name, the API returns as possible matches all
##' names that include the queried name as a possible synonym. This
##' function allows you to explore other synonyms for an accepted
##' name, and allows you to determine why the name you queried is
##' returning an accepted synonym.
##'
##' To list synonyms for a given taxonomic name, you need to provide
##' the object resulting from a call to the \code{tnrs_match_names}
##' function, as well as one of either the row number corresponding to
##' the name in this object, the name itself (as used in the original
##' query), or the ott_id listed for this name.
##'
##' @title List the synonyms for a given name
##' @param tax a data frame generated by the tnrs_match_names
##'     function
##' @param row_number the row number corresponding to the name for
##'     which to list the synonyms
##' @param taxon_name the taxon name corresponding to the name for
##'     which to list the synonyms
##' @param ott_id the ott id corresponding to the name for which to
##'     list the synonyms
##' @param ... currently ignored
##' @return a list whose elements are all synomym names (as vectors of
##'     character) for the taxonomic names that match the query (the
##'     names of the elements of the list).
##' @examples
##' \dontrun{
##'    echino <- tnrs_match_names(c("Diadema", "Acanthaster", "Fromia"))
##'    ## These 3 calls are identical
##'    synonyms(echino, taxon_name="Acanthaster")
##'    synonyms(echino, row_number=2)
##'    synonyms(echino, ott_id=337928)
##' }
##' @export

synonyms.match_names <- function(tax, row_number, taxon_name, ott_id, ...) {
    response <- tax
    i <- check_args_match_names(response, row_number, taxon_name, ott_id)

    res <- attr(response, "original_response")
    list_synonyms <- lapply(res$results[[i]]$match, function(x) {
        unlist(x$synonyms)
    })
    name_synonyms <- lapply(res$results[[i]]$match, function(x) {
        x$unique_name
    })
    names(list_synonyms) <- name_synonyms
    list_synonyms
}
