
##' Match taxonomic names to the Open Tree Taxonomy.
##'
##' Accepts one or more taxonomic names and returns information about
##' potential matches for these names to known taxa in the Open Tree
##' Taxononmy.
##'
##' This service uses taxonomic contexts to disambiguate homonyms and
##' misspelled names; a context may be specified using the
##' \code{context_name} argument. If no context is specified, then the
##' context will be inferred (i.e., the shallowest taxonomic context
##' that contains all unambiguous names in the input). Taxonomic
##' contexts are uncontested higher taxa that have been selected to
##' allow limits to be applied to the scope of TNRS searches
##' (e.g. 'match names only within flowering plants'). Once a context
##' has been identified (either user-specified or inferred), all taxon
##' name matches will performed only against taxa within that
##' context. For a list of available taxonomic contexts, see
##' \code{\link{tnrs_contexts}}.
##'
##' A name is considered unambiguous if it is not a synonym and has
##' only one exact match to any taxon name in the entire taxonomy.
##'
##' Several functions listed in the \sQuote{See also} section can be
##' used to inspect and manipulate the object generated by this
##' function.
##'
##'
##' @title Match names to the Open Tree Taxonomy
##' @param names taxon names to be queried (character vector)
##' @param context_name name of the taxonomic context to be searched
##'     (length-one character vector). Must match (case sensitive) one
##'     of the values returned by \code{\link{tnrs_contexts}}.
##' @param do_approximate_matching A logical indicating whether or not
##'     to perform approximate string (a.k.a. \dQuote{fuzzy})
##'     matching. Using \code{FALSE} will greatly improve
##'     speed. Default, however, is \code{TRUE}.
##' @param ids An array of ids to use for identifying names. These
##'     will be assigned to each name in the names array. If ids is
##'     provided, then ids and names must be identical in length.
##' @param include_deprecated A boolean indicating whether or not to
##'     include deprecated taxa in the search.
##' @param include_dubious Whether to include so-called 'dubious'
##'     taxa--those which are not accepted by OTT.
##' @param ...  additional arguments to customize the API request (see
##'     \code{\link{rotl}} package documentation).
##' @return A data frame summarizing the results of the query. The
##'     original query output is appended as an attribute to the
##'     returned object (and can be obtained using \code{attr(object,
##'     "original_response")}).
##' @seealso \code{\link{inspect_match_names}},
##'     \code{\link{update_match_names}},
##'     \code{\link{list_synonyms_match_names}}.
##' @examples \dontrun{
##'  deuterostomes <- tnrs_match_names(names=c("echinodermata", "xenacoelomorpha",
##'                                             "chordata", "hemichordata"))
##' }
##' @export
tnrs_match_names <- function(names = NULL, context_name = NULL,
                             do_approximate_matching = TRUE,
                             ids = NULL, include_deprecated = FALSE,
                             include_dubious = FALSE, ...) {

    if (!is.null(context_name) &&
        !context_name %in% unlist(tnrs_contexts(...))) {
        stop("The \'context_name\' is not valid. Check possible values using tnrs_contexts()")
    }

    res <- .tnrs_match_names(names = names, context_name = context_name,
                             do_approximate_matching = do_approximate_matching,
                             ids = ids, include_deprecated = include_deprecated,
                             include_dubious = include_dubious, ...)

    check_tnrs(res)
    summary_match <- do.call("rbind", lapply(res$results, function(x) {
        searchStr <- x$matches[[1]]$search_string
        uniqNames <- x$matches[[1]]$unique_name
        approxMatch <- x$matches[[1]]$is_approximate_match
        ott_id <- x$matches[[1]]$'ot:ottId'
        isSynonym <- x$matches[[1]]$is_synonym
        isDeprecated <- x$matches[[1]]$is_deprecated
        nMatch <- length(x$match)
        c(searchStr, uniqNames, approxMatch, ott_id, nMatch, isSynonym, isDeprecated)
    }))
    summary_match <- data.frame(summary_match, stringsAsFactors=FALSE)
    names(summary_match) <- c("search_string", "unique_name", "approximate_match",
                              "ott_id", "number_matches", "is_synonym", "is_deprecated")
    summary_match$search_string <- gsub("\\\\", "", summary_match$search_string)
    summary_match <- summary_match[match(tolower(names), summary_match$search_string), ]
    attr(summary_match, "original_order") <- as.numeric(rownames(summary_match))
    rownames(summary_match) <- NULL
    attr(summary_match, "original_response") <- res
    summary_match
}

check_tnrs <- function(req) {
    if (length(req$results) < 1) {
        stop("Nothing returned")
    }
    if (length(req$unmatched_name_ids)) {
        warning(paste(req$unmatched_name_ids, collapse=", "), " are not matched")
    }
}

##' This function returns a list of pre-defined taxonomic contexts
##' (i.e. clades) which can be used to limit the scope of tnrs
##' queries.
##'
##' Taxonomic contexts are available to limit the scope of TNRS
##' searches. These contexts correspond to uncontested higher taxa
##' such as 'Animals' or 'Land plants'. This service returns a list
##' containing all available taxonomic context names, which may be
##' used as input (via the \code{context_name} argument in other
##' functions) to limit the search scope of other services including
##' \code{\link{tnrs_match_names}}.
##' @title TNRS contexts
##' @param ...  additional arguments to customize the API request (see
##'     \code{\link{rotl}} package documentation).
##' @return Returns invisibly a list for each major clades (e.g.,
##'     animals, microbes, plants, fungi, life) whose elements
##'     contains the possible contexts.
##' @export

tnrs_contexts <- function(...) {
    res <- .tnrs_contexts(...)
    class(res) <- "tnrs_contexts"
    res
}

##' @export
print.tnrs_contexts <- function(x, ...) {
    cat("Possible contexts:\n")
    lapply(x, function(t) {
        res <- unlist(t)
        cat("  ", res[1], "\n")
        if (length(res) > 1)
            lapply(seq(2, length(t), by = 5), function(l) {
                m <- ifelse(l + 5 <= length(t), l+5, length(t))
                cat("     ", paste(t[l:m], collapse = ", "), "\n")
            })
    })
}

##' Return a taxonomic context given a list of taxonomic names
##'
##' Find the least inclusive taxonomic context that includes all the
##' unambiguous names in the input set. Unambiguous names are names
##' with exact matches to non-homonym taxa. Ambiguous names (those
##' without exact matches to non-homonym taxa) are indicated in
##' results.
##'
##' @title Infer the taxonomic context from a list of names
##' @param names Vector of taxon names.
##' @param ...  additional arguments to customize the API request (see
##'     \code{\link{rotl}} package documentation).
##' @return A list including the context name, the context ott id and
##'     possibly the names in the query that have an ambiguous
##'     taxonomic meaning in the query.
##' @examples
##' \dontrun{
##' res <- tnrs_infer_context(names=c("Stellula calliope", "Struthio camelus"))
##' }
##' @export
tnrs_infer_context <- function(names=NULL, ...) {
    res <- .tnrs_infer_context(names = names, ...)
    return(res)
}
